# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a48ab5a5da40b67d25aa2b63ff50a42bd1b2abd54f9ed9ff0c4af4fd2e55a83f1139d8628196799ebfbaaf67d57512688796fb94409aab0993cadcece32e6b

test:
  secret_key_base: f0fdd0c7d1a255d5661bac643c3f74a3ea5052d0cd4b66eca1c8881acf2d6194ad8cce54d6e842741987afb978e1b0ab797995ed06a3b7cec7b103b026bc415f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
